name: Your name here
description: Provide a description here

branding:
  color: blue
  icon: activity

inputs:
  milliseconds:
    required: true
    description: input description here
    default: default value if applicable

runs:
  using: node24
  main: dist/main.js
